# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a4b26d8ff2e9c8fe42c3d15172670ed9616bfe7f627aced393798d95cfaff0d3ed4dcf4319cc5d5a5c2e2c1f386ff81d934d94b581515d544a3bd47205668ab

test:
  secret_key_base: 4ddf4657538a86b0f39cd2c92afdbb7066d0af96255a1cd28b8b3db66532d0a8ec9f52c67248fe6ce8f61daca71d4c3f6dff70f16202fa2356004ece0e52aa72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
